ldconfig permission try sudo

diff --git a/compile_install_linux b/compile_install_linux
--- a/compile_install_linux
+++ b/compile_install_linux
@@ -156,8 +156,12 @@ if (ldconfig --version >/dev/null 2>&1); then
         exit 1
     fi
 else
-    echo "Cannot execute command ldconfig, make sure it is available and you have permission to use this command."
-    exit 1
+    if (sudo ldconfig -p | grep libstdc++ >/dev/null && ldconfig -p | grep libgcc_s >/dev/null && ldconfig -p | grep libc >/dev/null); then
+        echo "GCC libraries found in the system."
+    else
+        echo "Cannot execute command ldconfig, make sure it is available and you have permission to use this command."
+        exit 1
+    fi
 fi
 echo "Done."
 
